#!/usr/bin/python

import GitSvnServer
import optparse


version = "pre-alpha"


description = \
"""This program attempts to server one or more git repositories using the
Subversion svn:// protocol.
"""

epilog = \
"""WARNING: Currently there is a lot that doesn't work at all, doesn't work
properly, or doesn't handle errors.  Anyone who configures this program to
serve a git repository that isn't disposable is possibly insane, and certainly
on the own.
"""


def main():
    parser = optparse.OptionParser(description = description,
                                   epilog = epilog,
                                   version = version)

    parser.add_option('-c', '--config', metavar='CONFIG', default=None,
                      help='Load configuration from CONFIG')

    parser.add_option('-i', '--ip', metavar='ADDRESS', default=None,
                      help='Bind to the specifed IP address (can be v6 if '
                      'supported by Python).  The default is all addresses.')

    parser.add_option('-p', '--port', metavar='PORT', default=3690, type='int',
                      help='Bind to the specified port number, instead of '
                      'the default SVN port.')

    parser.add_option('-f', '--foreground', default=False, action="store_true",
                      help='Run in the foreground instead of as a daemon.')

    parser.add_option('-d', '--debug', default=False, action="store_true",
                      help='Run in debug mode (implies --foreground).')

    parser.add_option('-l', '--log', default='svnserver.log',
                      help='File to log to if running as daemon.')

    options, args = parser.parse_args()

    GitSvnServer.config.load(options.config)

    server = GitSvnServer.SvnServer(log = options.log,
                                    ip = options.ip,
                                    port = options.port)
    server.start(foreground = options.foreground,
                 debug = options.debug)


if __name__ == "__main__":
    main()
