#!/usr/bin/python

import GitSvnServer

def main():
    GitSvnServer.config.load('test.cfg')

    server = GitSvnServer.SvnServer()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass

if __name__ == "__main__":
    main()
